# ═══════════════════════════════════════════════════════════════════
# CATÁLOGO COMPLETO — Essen + Tupi
# Imágenes: og:image obtenidas directamente de cada página de producto
# ═══════════════════════════════════════════════════════════════════

BASE = "https://www.essen.com.py/imgs/w800/contenido/objetos/3/"

def e(f): return BASE + f   # helper Essen image
def t(cod): return f"https://www.tupi.com.py/imgs/w400/contenido/productos/{cod}.jpg"

CATALOGO = [

    # ──────────────────────────────────────────
    #  E S S E N  — Línea Cera Forte Terra
    # ──────────────────────────────────────────
    {"id":"essen-cf-001","marca":"Essen","linea":"Cera Forte Terra","nombre":"Sartén 24cm Cera Forte","tipo":"Sartén","precio_ref":0,"comensales":"4","capacidad":"—","descripcion":"Sartén cerámica reforzada sin PFOA ni PTFE. Alta resistencia al rayado.","imagen":e("Sarte%CC%81n%2024CM%20CERA%CC%81MICA.jpg"),"url":"https://www.essen.com.py/producto/sarten-24cm-P1204.html","categoria":"Sartenes"},
    {"id":"essen-cf-002","marca":"Essen","linea":"Cera Forte Terra","nombre":"Cacerola 18cm Cera Forte","tipo":"Cacerola","precio_ref":0,"comensales":"2","capacidad":"1.8 L","descripcion":"Cacerola pequeña cerámica para 2 personas. Cocción saludable sin químicos.","imagen":e("Cacerola%2018CM%20CERA%CC%81MICA.jpg"),"url":"https://www.essen.com.py/producto/cacerola-18cm-P1205.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-cf-003","marca":"Essen","linea":"Cera Forte Terra","nombre":"Cacerola 24cm Cera Forte","tipo":"Cacerola","precio_ref":0,"comensales":"4-5","capacidad":"4.5 L","descripcion":"Recubrimiento Cera Forte reforzado. Máxima durabilidad antiadherente.","imagen":e("Cacerola%2024CM%20CERA%CC%81MICA.jpg"),"url":"https://www.essen.com.py/producto/cacerola-24cm-P1203.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-cf-004","marca":"Essen","linea":"Cera Forte Terra","nombre":"Cuadrada 29cm Terra Cerámica","tipo":"Cacerola","precio_ref":0,"comensales":"6","capacidad":"6 L","descripcion":"Cacerola cuadrada cerámica. Perfecta para panes, budines y asados.","imagen":e("Cuadrada%2029cm%20terra.jpg"),"url":"https://www.essen.com.py/producto/cuadrada-29cm-terra-ceramica-P1216.html","categoria":"Ollas y Cacerolas"},

    # ── Línea a Inducción
    {"id":"essen-ind-001","marca":"Essen","linea":"Línea a Inducción","nombre":"Cacerola c/ tapa sartén 24cm Nuit Inducción","tipo":"Cacerola","precio_ref":0,"comensales":"4-5","capacidad":"4.5 L","descripcion":"Compatible con cocinas a inducción. Base especial de acero. Diseño Nuit negro.","imagen":e("CACEROLA%20CON%20TAPA%20SARTEN%2024CM%20NUIT%20INDUCCI%C3%93N.jpg"),"url":"https://www.essen.com.py/producto/cacerola-con-tapa-sarten-24cm-nuit-P1215.html","categoria":"Ollas y Cacerolas"},

    # ── Contemporánea Capri
    {"id":"essen-cap-001","marca":"Essen","linea":"Contemporánea Capri","nombre":"Cacerola 24cm Capri","tipo":"Cacerola","precio_ref":0,"comensales":"4-5","capacidad":"4.5 L","descripcion":"La más vendida de Essen. Ideal para hornos, sopas, tortas y guisos.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalCACEROLA%2024CM%20CAPRI.jpg"),"url":"https://www.essen.com.py/producto/cacerola-24cm-P1192.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-cap-002","marca":"Essen","linea":"Contemporánea Capri","nombre":"Sartén 24cm Capri","tipo":"Sartén","precio_ref":0,"comensales":"4","capacidad":"—","descripcion":"Sartén antiadherente de aluminio fundido. Diseño Capri con acabado moderno.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalSART%C3%89N%2024CM%20CAPRI.jpg"),"url":"https://www.essen.com.py/producto/sarten-24cm-P1186.html","categoria":"Sartenes"},
    {"id":"essen-cap-003","marca":"Essen","linea":"Contemporánea Capri","nombre":"Cacerola con mango 18cm Capri","tipo":"Cacerola","precio_ref":0,"comensales":"2","capacidad":"1.8 L","descripcion":"Cacerola pequeña con mango ergonómico. Para salsas y guarniciones.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalCACEROLA%2018CM%20CAPRI.jpg"),"url":"https://www.essen.com.py/producto/cacerola-con-mango-18cm-P1193.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-cap-004","marca":"Essen","linea":"Contemporánea Capri","nombre":"Cacerola 28cm Capri","tipo":"Cacerola","precio_ref":0,"comensales":"6-8","capacidad":"7.5 L","descripcion":"Ideal para familias grandes. Al vapor, horno, frituras y guisos.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalCACEROLA%2028CM.jpg"),"url":"https://www.essen.com.py/producto/cacerola-28cm-P1191.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-cap-005","marca":"Essen","linea":"Contemporánea Capri","nombre":"Sartén 28cm Capri","tipo":"Sartén","precio_ref":0,"comensales":"6","capacidad":"—","descripcion":"Sartén grande para asados, frituras y salteados. Aluminio de alta resistencia.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalSARTEN%2028CM%20CAPRI.jpg"),"url":"https://www.essen.com.py/producto/sarten-28cm-P1185.html","categoria":"Sartenes"},
    {"id":"essen-cap-006","marca":"Essen","linea":"Contemporánea Capri","nombre":"Cacerola Cuadrada 29cm Capri","tipo":"Cacerola","precio_ref":0,"comensales":"6","capacidad":"6 L","descripcion":"Cacerola cuadrada para panes, budines y asados. Diseño exclusivo Capri.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalMesa%20de%20trabajo%206%20%281%29.jpg"),"url":"https://www.essen.com.py/producto/cacerola-cuadrada-29cm-P1190.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-cap-007","marca":"Essen","linea":"Contemporánea Capri","nombre":"Set Utensilios Uso General Capri","tipo":"Set Utensilios","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Juego completo de utensilios de cocina línea Capri. Espátulas, cucharones y accesorios.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalSET%20DE%20UTENSILIOS%20DE%20USO%20GENERAL_1715975332457852.jpg"),"url":"https://www.essen.com.py/producto/set-de-utensilios-de-uso-general-capri-P1183.html","categoria":"Utensilios"},
    {"id":"essen-cap-008","marca":"Essen","linea":"Contemporánea Capri","nombre":"Flip 2.1 Capri","tipo":"Flip","precio_ref":0,"comensales":"2-3","capacidad":"—","descripcion":"Doble sartén para tortillas y omelettes. Se cocina por ambos lados sin voltear.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalFLIP%202.1%20CAPRI.jpg"),"url":"https://www.essen.com.py/producto/flip-21-P1188.html","categoria":"Especiales"},
    {"id":"essen-cap-009","marca":"Essen","linea":"Contemporánea Capri","nombre":"Cacerola 8 litros Capri","tipo":"Cacerola","precio_ref":0,"comensales":"8+","capacidad":"8 L","descripcion":"La más grande de la línea Capri. Para cocciones masivas, sopas y guisos.","imagen":e("Escalado%20IMG%20%20Capri%20%20Web%20institucionalMesa%20de%20trabajo%202.jpg"),"url":"https://www.essen.com.py/producto/cacerola-8-litros-P1197.html","categoria":"Ollas y Cacerolas"},

    # ── Contemporánea Terra
    {"id":"essen-ter-001","marca":"Essen","linea":"Contemporánea Terra","nombre":"Cacerola Cuadrada 29cm Terra","tipo":"Cacerola","precio_ref":0,"comensales":"6","capacidad":"6 L","descripcion":"Cacerola cuadrada cerámica natural. Para panes, pizzas y asados al horno.","imagen":e("terracacerolacuadrada30cm.jpg"),"url":"https://www.essen.com.py/producto/cacerola-cuadrada-29cm-P1035.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-ter-002","marca":"Essen","linea":"Contemporánea Terra","nombre":"Sartén 24cm Terra","tipo":"Sartén","precio_ref":0,"comensales":"4","capacidad":"—","descripcion":"Sartén cerámica natural Terra. Antiadherente sin PFOA.","imagen":e("terrasarten24cm.jpg"),"url":"https://www.essen.com.py/producto/sarten-24cm-P1026.html","categoria":"Sartenes"},
    {"id":"essen-ter-003","marca":"Essen","linea":"Contemporánea Terra","nombre":"Cacerola 18cm con mango Terra","tipo":"Cacerola","precio_ref":0,"comensales":"2","capacidad":"1.8 L","descripcion":"Cacerola con mango cerámica Terra para porciones individuales y salsas.","imagen":e("terracacerolaconmango18cm.jpg"),"url":"https://www.essen.com.py/producto/cacerola-18cm-con-mango-P1024.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-ter-004","marca":"Essen","linea":"Contemporánea Terra","nombre":"Cacerola 24cm Terra","tipo":"Cacerola","precio_ref":0,"comensales":"4-5","capacidad":"4.5 L","descripcion":"Cacerola cerámica natural. Cocción sana, concentra vitaminas y minerales.","imagen":e("terracacerola24cm.jpg"),"url":"https://www.essen.com.py/producto/cacerola-24cm-P1025.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-ter-005","marca":"Essen","linea":"Contemporánea Terra","nombre":"Sartén Express Terra","tipo":"Sartén","precio_ref":0,"comensales":"3","capacidad":"—","descripcion":"Sartén express Terra para preparaciones rápidas con mínimo aceite.","imagen":e("Sarten%20express_Terra%20%281%29_1667503850546263.png"),"url":"https://www.essen.com.py/producto/sarten-express-P1124.html","categoria":"Sartenes"},
    {"id":"essen-ter-006","marca":"Essen","linea":"Contemporánea Terra","nombre":"Sartén 28cm Terra","tipo":"Sartén","precio_ref":0,"comensales":"6","capacidad":"—","descripcion":"Sartén grande cerámica Terra. Alta resistencia y cocción uniforme.","imagen":e("Sar%2028%20Terra.jpg"),"url":"https://www.essen.com.py/producto/sarten-28cm-P1088.html","categoria":"Sartenes"},
    {"id":"essen-ter-007","marca":"Essen","linea":"Contemporánea Terra","nombre":"Cacerola 28cm Terra","tipo":"Cacerola","precio_ref":0,"comensales":"6-8","capacidad":"7.5 L","descripcion":"Cacerola cerámica grande Terra para familias numerosas.","imagen":e("Cac%2028%20Terra.jpg"),"url":"https://www.essen.com.py/producto/cacerola-28cm-P1086.html","categoria":"Ollas y Cacerolas"},
    {"id":"essen-ter-008","marca":"Essen","linea":"Contemporánea Terra","nombre":"Flip 2.1 Terra","tipo":"Flip","precio_ref":0,"comensales":"2-3","capacidad":"—","descripcion":"Doble sartén cerámica para tortillas, crepes y omelettes sin voltear.","imagen":e("Flip%2021%20Terra.jpg"),"url":"https://www.essen.com.py/producto/flip-21-P1173.html","categoria":"Especiales"},

    # ── Nuit
    {"id":"essen-nuit-001","marca":"Essen","linea":"Nuit","nombre":"Set Nuit 24cm","tipo":"Set","precio_ref":0,"comensales":"4-5","capacidad":"4.5 L","descripcion":"Set completo Nuit: cacerola + sartén con tapa. Diseño negro premium.","imagen":e("Set%20Nuit.png"),"url":"https://www.essen.com.py/producto/set-nuit-24-cm-P1145.html","categoria":"Sets"},
    {"id":"essen-nuit-002","marca":"Essen","linea":"Nuit","nombre":"Flip Nuit","tipo":"Flip","precio_ref":0,"comensales":"2-3","capacidad":"—","descripcion":"Flip doble en acabado Nuit negro mate. Tortillas perfectas en ambos lados.","imagen":e("Flip%20Nuit.jpg"),"url":"https://www.essen.com.py/producto/flip-nuit-P1199.html","categoria":"Especiales"},
    {"id":"essen-nuit-003","marca":"Essen","linea":"Nuit","nombre":"Set Nuit 28cm","tipo":"Set","precio_ref":0,"comensales":"6-8","capacidad":"7.5 L","descripcion":"Set Nuit grande 28cm. Cacerola + sartén tapa. Negro mate elegante.","imagen":e("Set%20Nuit%2028cm%202023.jpg"),"url":"https://www.essen.com.py/producto/set-nuit-28-cm-P1109.html","categoria":"Sets"},

    # ── Ediciones Especiales
    {"id":"essen-esp-001","marca":"Essen","linea":"Ediciones Especiales","nombre":"Soporte Plegable Disco/Grill","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Soporte plegable para disco y grill. Cocina a la parrilla con tu Essen.","imagen":e("Soporte%20Disco%20Grill%20%281%29.png"),"url":"https://www.essen.com.py/producto/soporte-plegable-P1135.html","categoria":"Accesorios"},

    # ── Complementos
    {"id":"essen-comp-001","marca":"Essen","linea":"Complementos","nombre":"Cestillo Freidor","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Cestillo para freír en cacerolas Essen. Milanesas, papas y tempuras.","imagen":e("freidorparacacerola2.jpg"),"url":"https://www.essen.com.py/producto/cestillo-freidor-P292.html","categoria":"Accesorios"},
    {"id":"essen-comp-002","marca":"Essen","linea":"Complementos","nombre":"Budineras Terra x2","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set de 2 budineras cerámica Terra para flanes, budines y soufflés.","imagen":e("setdebudineras2.jpg"),"url":"https://www.essen.com.py/producto/budineras-terra-x2-P947.html","categoria":"Accesorios"},
    {"id":"essen-comp-003","marca":"Essen","linea":"Complementos","nombre":"Vaporizador 18/28cm","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Vaporizador compatible con cacerolas 18 y 28cm. Cocción al vapor saludable.","imagen":e("Vaporizador%20%281%29.png"),"url":"https://www.essen.com.py/producto/vaporizador-1828cm-P1154.html","categoria":"Accesorios"},
    {"id":"essen-comp-004","marca":"Essen","linea":"Complementos","nombre":"Savarin Terra 18cm","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Molde savarin cerámica 18cm para tortas en anillo, flanes y budines.","imagen":e("terrasavarin18cm2.jpg"),"url":"https://www.essen.com.py/producto/savarin-18cm-terra-P1058.html","categoria":"Accesorios"},
    {"id":"essen-comp-005","marca":"Essen","linea":"Complementos","nombre":"Savarin Terra 24cm","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Molde savarin cerámica 24cm. Tortas en anillo, flanes y budines.","imagen":e("terrasavarin24cm2.jpg"),"url":"https://www.essen.com.py/producto/savarin-24cm-terra-P1057.html","categoria":"Accesorios"},
    {"id":"essen-comp-006","marca":"Essen","linea":"Complementos","nombre":"Savarin Terra 28cm","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Molde savarin cerámica 28cm para preparaciones grandes.","imagen":e("terrasavarin28cm2.jpg"),"url":"https://www.essen.com.py/producto/savarin-28cm-terra-P1059.html","categoria":"Accesorios"},

    # ── Bazar Premium
    {"id":"essen-baz-001","marca":"Essen","linea":"Bazar Premium","nombre":"Cuchillo Chef","tipo":"Cuchillo","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Cuchillo chef de acero inoxidable. Para cortar, picar y rebanar profesionalmente.","imagen":e("Cuchillo%20Chef_01_1741890165557769.jpg"),"url":"https://www.essen.com.py/producto/cuchillo-chef-P1206.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-002","marca":"Essen","linea":"Bazar Premium","nombre":"Cuchillo Utilitario","tipo":"Cuchillo","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Cuchillo utilitario multiuso. Hoja de acero inoxidable, mango ergonómico.","imagen":e("CuchilloUtility_1733248400334544.jpg"),"url":"https://www.essen.com.py/producto/cuchillo-utilitario-P1207.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-003","marca":"Essen","linea":"Bazar Premium","nombre":"Cuchillo Carving","tipo":"Cuchillo","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Cuchillo carving para trinchar carnes y aves. Hoja larga y flexible.","imagen":e("CuchilloCarving_01%281%29_1733248435455947.jpg"),"url":"https://www.essen.com.py/producto/cuchillo-carving-P1208.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-004","marca":"Essen","linea":"Bazar Premium","nombre":"Rallador Grano Fino","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Rallador de acero inoxidable grano fino para quesos duros y nuez moscada.","imagen":e("Rallador%20grano%20fino.jpg"),"url":"https://www.essen.com.py/producto/rallador-grano-fino-P1219.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-005","marca":"Essen","linea":"Bazar Premium","nombre":"Rallador Grano Grueso","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Rallador grano grueso para zanahorias, zapallo y quesos blandos.","imagen":e("RALLADOR%20DE%20MANO%20GRANO%20GRUESO.jpg"),"url":"https://www.essen.com.py/producto/rallador-grano-grueso-P1217.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-006","marca":"Essen","linea":"Bazar Premium","nombre":"Rallador Grano Medio","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Rallador grano medio. Versátil para distintas preparaciones.","imagen":e("RALLADOR%20DE%20MANO%20GRANO%20MEDIO.jpg"),"url":"https://www.essen.com.py/producto/rallador-grano-medio-P1218.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-007","marca":"Essen","linea":"Bazar Premium","nombre":"Tabla de Bambú 30x40","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Tabla de bambú natural 30x40cm. Resistente, antibacteriana y ecológica.","imagen":e("Tabla%20Bambu%2030x40.jpg"),"url":"https://www.essen.com.py/producto/tabla-de-bambu-30-x-40-P1220.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-008","marca":"Essen","linea":"Bazar Premium","nombre":"Tabla de Bambú 30x30","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Tabla de bambú cuadrada 30x30cm. Liviana y duradera.","imagen":e("Tabla%20de%20Bambu%2030x30.jpg"),"url":"https://www.essen.com.py/producto/tabla-de-bambu-30-x-30-P1221.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-009","marca":"Essen","linea":"Bazar Premium","nombre":"Limpiador Abrillantador","tipo":"Limpiador","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Limpiador abrillantador a base de aloe vera. Restaura el brillo de las piezas Essen.","imagen":e("67700703.jpg"),"url":"https://www.essen.com.py/producto/limpiador-abrillantador-P342.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-010","marca":"Essen","linea":"Bazar Premium","nombre":"Limpiador Desengrasante","tipo":"Limpiador","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Desengrasante naranja Essen con fragancia cítrica. Limpieza profunda sin rayar.","imagen":e("67700704.jpg"),"url":"https://www.essen.com.py/producto/limpiador-desengrasante-P343.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-011","marca":"Essen","linea":"Bazar Premium","nombre":"Set Utensilios para Pastas","tipo":"Set Utensilios","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set de utensilios especial para pastas: cortadores, espátulas y más.","imagen":e("utenisliospastas_1522756935710230.jpg"),"url":"https://www.essen.com.py/producto/set-de-utensilios-para-pastas-P370.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-012","marca":"Essen","linea":"Bazar Premium","nombre":"Vaso Medidor","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Vaso medidor de aluminio con escala grabada. Lectura lateral y helicoidal.","imagen":e("vaso-medidor-essen-cod-60050028.jpg"),"url":"https://www.essen.com.py/producto/vaso-medidor-P364.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-013","marca":"Essen","linea":"Bazar Premium","nombre":"Set Utensilios Uso General Negro","tipo":"Set Utensilios","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set de utensilios de cocina color negro. Espátulas, cucharones y accesorios.","imagen":e("main60050123.jpg"),"url":"https://www.essen.com.py/producto/set-de-utensilios-de-uso-general-negro-P988.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-014","marca":"Essen","linea":"Bazar Premium","nombre":"Corta Pizza","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Cortapizzas de plástico alta resistencia con mango ergonómico antideslizante.","imagen":e("corta-pizza-essen-cod-60050078.jpg"),"url":"https://www.essen.com.py/producto/corta-pizza-P454.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-015","marca":"Essen","linea":"Bazar Premium","nombre":"Tazas Medidoras de Aluminio","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set 4 tazas medidoras de aluminio apilables: 1 taza, 1/2, 1/3 y 1/4.","imagen":e("medidoresEssen.jpg"),"url":"https://www.essen.com.py/producto/tazas-medidoras-de-aluminio-P731.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-016","marca":"Essen","linea":"Bazar Premium","nombre":"Pelador de Vegetales","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Pelador con mango ergonómico antideslizante. Apto para zurdos y diestros.","imagen":e("60050021-pelador-de-vegetales.jpg"),"url":"https://www.essen.com.py/producto/pelador-de-vegetales-P856.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-017","marca":"Essen","linea":"Bazar Premium","nombre":"Abrelatas 5 en 1","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Abridor multiuso 5 en 1. Abre latas, botellas, tapas y más.","imagen":e("main600501091507926266679254.png"),"url":"https://www.essen.com.py/producto/abrelatas-5-en-1-P983.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-018","marca":"Essen","linea":"Bazar Premium","nombre":"Estira Masas Beige","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Rodillo de plástico gran resistencia para estirar masas dentro de la pieza.","imagen":e("60050165.jpg"),"url":"https://www.essen.com.py/producto/estira-masas-beige-P453.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-019","marca":"Essen","linea":"Bazar Premium","nombre":"Set Utensilios para Carnes","tipo":"Set Utensilios","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set de utensilios para carnes: pinzas, tenedor y espátula especial.","imagen":e("main60050126_1508271136704697_1674070279333805.jpg"),"url":"https://www.essen.com.py/producto/set-de-utensilios-para-carnes-P991.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-020","marca":"Essen","linea":"Bazar Premium","nombre":"Set Coladores Metálicos x2","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"2 coladores de acero inoxidable: mediano 10cm y chico 6.5cm.","imagen":e("60050114.jpg"),"url":"https://www.essen.com.py/producto/set-coladores-metalicos-x2-P998.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-021","marca":"Essen","linea":"Bazar Premium","nombre":"Bombilla Neo","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Bombilla de mate Neo de acero inoxidable con filtro y cuchara en U.","imagen":e("60050120.jpg"),"url":"https://www.essen.com.py/producto/bombilla-neo-P1003.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-022","marca":"Essen","linea":"Bazar Premium","nombre":"Multiprocesador de Vegetales","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Pica frutas, verduras y frutos secos. Contenedor transparente hermético.","imagen":e("Multiprocesadordevegatalesweb.jpg"),"url":"https://www.essen.com.py/producto/multiprocesador-de-vegetales-P986.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-023","marca":"Essen","linea":"Bazar Premium","nombre":"Espátula y Batidor Silicona Terra","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set espátula + batidor de silicona resistente al calor hasta 220°C.","imagen":e("60050161web.jpg"),"url":"https://www.essen.com.py/producto/espatula-y-batidor-de-silicona-terra-P1068.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-024","marca":"Essen","linea":"Bazar Premium","nombre":"Centrifugador de Vegetales","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Centrifugador manual para secar lechugas y hojas verdes sin mojarlas.","imagen":e("CentrifugadevegetalesWEB.jpg"),"url":"https://www.essen.com.py/producto/centrifugador-de-vegetales-P1019.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-025","marca":"Essen","linea":"Bazar Premium","nombre":"Tabla de Picar Gris 35x25","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Tabla bifaz antibacterial con indicador de tipo de alimento. Apoyos antideslizantes.","imagen":e("60050166.jpg"),"url":"https://www.essen.com.py/producto/tabla-de-picar-gris-35x25-P1128.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-026","marca":"Essen","linea":"Bazar Premium","nombre":"Tarros de Almacén","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Tarros herméticos apilables con tapa aptas como tazas medidoras.","imagen":e("tarros-de-almacen-apilables-essen-cod-60050045.jpg"),"url":"https://www.essen.com.py/producto/tarros-de-almacen-P362.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-027","marca":"Essen","linea":"Bazar Premium","nombre":"Asas de Silicona Terra","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Par de asas de silicona Terra resistentes a altas temperaturas para piezas Essen.","imagen":e("60050142asasgrisesweb.jpg"),"url":"https://www.essen.com.py/producto/asas-de-silicona-terra-P1031.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-028","marca":"Essen","linea":"Bazar Premium","nombre":"Set Utensilios Uso General Terra","tipo":"Set Utensilios","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set completo de utensilios línea Terra con acabado cerámica.","imagen":e("Utensilios%20terra.jpg"),"url":"https://www.essen.com.py/producto/set-de-utensilio-de-uso-general-terra-P1078.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-029","marca":"Essen","linea":"Bazar Premium","nombre":"Set Mate Neo Terra","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Set para mate: interior acero inoxidable, tapa flexible para bombilla. Diseño Terra.","imagen":e("60050150.jpg"),"url":"https://www.essen.com.py/producto/set-mate-neo-terra-P1030.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-030","marca":"Essen","linea":"Bazar Premium","nombre":"Molinillo de Especias Triple","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Molinillo cerámico triple con 3 recipientes intercambiables y regulación de grosor.","imagen":e("molinillo-de-especie-striple-essen-cod-6005012.jpg"),"url":"https://www.essen.com.py/producto/molinillo-de-especias-triple-P450.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-031","marca":"Essen","linea":"Bazar Premium","nombre":"Mandolina","tipo":"Accesorio","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Mandolina para cortar vegetales en láminas uniformes con múltiples grosores.","imagen":e("mandolina-essen-cod-60050008.jpg"),"url":"https://www.essen.com.py/producto/mandolina-P615.html","categoria":"Bazar Premium"},
    {"id":"essen-baz-032","marca":"Essen","linea":"Bazar Premium","nombre":"Anafe a Inducción","tipo":"Electrodoméstico","precio_ref":0,"comensales":"—","capacidad":"—","descripcion":"Anafe a inducción portable compatible con la línea Nuit. Eficiente y preciso.","imagen":e("ANAFE%20A%20INDUCCI%C3%93N.jpg"),"url":"https://www.essen.com.py/producto/anafe-P1202.html","categoria":"Bazar Premium"},

    # ══════════════════════════════════════════════
    #  T U P I  — Lavarropas
    # ══════════════════════════════════════════════
    {"id":"tupi-lav-001","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Samsung 8kg Inverter","tipo":"Lavarropas","precio_ref":1600000,"comensales":"—","capacidad":"8 kg","descripcion":"Inverter 40% ahorro energético. Sistema Dual Storm, Filtro Mágico, inicio diferido.","imagen":t("122280"),"url":"https://www.tupi.com.py/producto/122280/","categoria":"Lavarropas"},
    {"id":"tupi-lav-002","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Whirlpool 10.1kg Plata","tipo":"Lavarropas","precio_ref":2152000,"comensales":"—","capacidad":"10.1 kg","descripcion":"Lavado rápido 26 min. Eco-friendly, tapa vidrio templado, 850 RPM, carga superior.","imagen":t("36027"),"url":"https://www.tupi.com.py/producto/36027/","categoria":"Lavarropas"},
    {"id":"tupi-lav-003","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Whirlpool 13kg Inverter Sand Gold","tipo":"Lavarropas","precio_ref":2909000,"comensales":"—","capacidad":"13 kg","descripcion":"Carga superior 13kg Inverter Sand Gold. 700 RPM, múltiples programas.","imagen":t("92970"),"url":"https://www.tupi.com.py/producto/92970/","categoria":"Lavarropas"},
    {"id":"tupi-lav-004","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas JAM Grace 6kg Carga Frontal","tipo":"Lavarropas","precio_ref":1881000,"comensales":"—","capacidad":"6 kg","descripcion":"Carga frontal 6kg, 15 programas, 1000 RPM, tambor inox, agua caliente incorporada.","imagen":t("106290"),"url":"https://www.tupi.com.py/producto/106290/","categoria":"Lavarropas"},
    {"id":"tupi-lav-005","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Electrolux 8kg Carga Frontal Blanco","tipo":"Lavarropas","precio_ref":3098000,"comensales":"—","capacidad":"8 kg","descripcion":"Carga frontal Electrolux 8kg. Eficiencia energética A+++, múltiples ciclos.","imagen":t("60346"),"url":"https://www.tupi.com.py/producto/60346/","categoria":"Lavarropas"},
    {"id":"tupi-lav-006","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Electrolux 6kg Carga Frontal","tipo":"Lavarropas","precio_ref":1912000,"comensales":"—","capacidad":"6 kg","descripcion":"Carga frontal Electrolux 6kg blanco. Eficiencia energética, motor inverter.","imagen":t("58992"),"url":"https://www.tupi.com.py/producto/58992/","categoria":"Lavarropas"},
    {"id":"tupi-lav-007","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Whirlpool 9kg Carga Frontal","tipo":"Lavarropas","precio_ref":2394000,"comensales":"—","capacidad":"9 kg","descripcion":"Carga frontal 9kg Whirlpool. Múltiples programas y centrifugado eficiente.","imagen":t("52773"),"url":"https://www.tupi.com.py/producto/52773/","categoria":"Lavarropas"},
    {"id":"tupi-lav-008","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas LG 13kg Inverter Carga Superior","tipo":"Lavarropas","precio_ref":0,"comensales":"—","capacidad":"13 kg","descripcion":"LG 13kg carga superior Inverter Direct Drive. Motor silencioso y eficiente.","imagen":t("98269"),"url":"https://www.tupi.com.py/producto/98269/","categoria":"Lavarropas"},
    {"id":"tupi-lav-009","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas JAM Alba 12kg Carga Superior Gris","tipo":"Lavarropas","precio_ref":2253000,"comensales":"—","capacidad":"12 kg","descripcion":"JAM 12kg 8 programas carga superior color gris. Gran capacidad familiar.","imagen":t("129446"),"url":"https://www.tupi.com.py/producto/129446/","categoria":"Lavarropas"},
    {"id":"tupi-lav-010","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Whirlpool 20kg Carga Superior","tipo":"Lavarropas","precio_ref":4369000,"comensales":"—","capacidad":"20 kg","descripcion":"Gran capacidad 20kg carga superior. Ideal para uso intensivo. 700 RPM.","imagen":t("84808"),"url":"https://www.tupi.com.py/producto/84808/","categoria":"Lavarropas"},
    {"id":"tupi-lav-011","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Samsung 19kg Eco Bubble Carga Superior","tipo":"Lavarropas","precio_ref":0,"comensales":"—","capacidad":"19 kg","descripcion":"Samsung 19kg tecnología Eco Bubble para lavado eficiente incluso en agua fría.","imagen":t("131680"),"url":"https://www.tupi.com.py/producto/131680/","categoria":"Lavarropas"},
    {"id":"tupi-lav-012","marca":"Tupi","linea":"Lavarropas","nombre":"Lavarropas Electrolux 14kg Paleta Carga Superior","tipo":"Lavarropas","precio_ref":3499000,"comensales":"—","capacidad":"14 kg","descripcion":"Electrolux 14kg carga superior a paleta, 12 programas, agua caliente incluida.","imagen":t("84395"),"url":"https://www.tupi.com.py/producto/84395/","categoria":"Lavarropas"},

    # ── Secarropas
    {"id":"tupi-sec-001","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas Electrolux 6kg Blanco","tipo":"Secarropas","precio_ref":2455000,"comensales":"—","capacidad":"6 kg","descripcion":"Secarropas carga frontal 6kg Electrolux blanco. Sensor de humedad, múltiples programas.","imagen":t("58991"),"url":"https://www.tupi.com.py/producto/58991/","categoria":"Secarropas"},
    {"id":"tupi-sec-002","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas Electrolux 6kg Gris","tipo":"Secarropas","precio_ref":2660000,"comensales":"—","capacidad":"6 kg","descripcion":"Secarropas carga frontal 6kg color gris. Eficiencia energética A++.","imagen":t("100458"),"url":"https://www.tupi.com.py/producto/100458/","categoria":"Secarropas"},
    {"id":"tupi-sec-003","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas Electrolux 9kg Blanco","tipo":"Secarropas","precio_ref":3109000,"comensales":"—","capacidad":"9 kg","descripcion":"Secarropas 9kg carga frontal, 14 programas. Control de temperatura avanzado.","imagen":t("95051"),"url":"https://www.tupi.com.py/producto/95051/","categoria":"Secarropas"},
    {"id":"tupi-sec-004","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas Whirlpool 15kg USA","tipo":"Secarropas","precio_ref":4399000,"comensales":"—","capacidad":"15 kg","descripcion":"Secarropas americano 15kg, 14 programas. Sistema de secado Heat Sense.","imagen":t("45349"),"url":"https://www.tupi.com.py/producto/45349/","categoria":"Secarropas"},
    {"id":"tupi-sec-005","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas Samsung Bespoke 17kg Black","tipo":"Secarropas","precio_ref":7798000,"comensales":"—","capacidad":"17 kg","descripcion":"Samsung Bespoke 17kg con sistema inteligente AI. Color Black premium.","imagen":t("112594"),"url":"https://www.tupi.com.py/producto/112594/","categoria":"Secarropas"},
    {"id":"tupi-sec-006","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas Colgante JAM 10kg Gris/Blanco","tipo":"Secarropas","precio_ref":889000,"comensales":"—","capacidad":"10 kg","descripcion":"Secarropas colgante 10kg, 4 programas. Ahorra espacio. Gris/Blanco.","imagen":t("151339"),"url":"https://www.tupi.com.py/producto/151339/","categoria":"Secarropas"},
    {"id":"tupi-sec-007","marca":"Tupi","linea":"Secarropas","nombre":"Secarropa y Calefactor Colgante Latina 10kg","tipo":"Secarropas","precio_ref":899000,"comensales":"—","capacidad":"10 kg","descripcion":"Secarropa colgante con función calefactor SR555. Doble uso, ahorro de espacio.","imagen":t("134128"),"url":"https://www.tupi.com.py/producto/134128/","categoria":"Secarropas"},
    {"id":"tupi-sec-008","marca":"Tupi","linea":"Secarropas","nombre":"Secarropas JAM 9kg Blanco","tipo":"Secarropas","precio_ref":2120000,"comensales":"—","capacidad":"9 kg","descripcion":"JAM SJC90 9kg 220V blanco. Secado eficiente con múltiples temperaturas.","imagen":t("83334"),"url":"https://www.tupi.com.py/producto/83334/","categoria":"Secarropas"},

    # ── Televisores
    {"id":"tupi-tv-001","marca":"Tupi","linea":"Televisores","nombre":"TV Midas 43\" FHD Smart Google TV","tipo":"Televisor","precio_ref":1677000,"comensales":"—","capacidad":"43\"","descripcion":"Smart TV Google TV 43\" Full HD LED Frameless. WiFi, Bluetooth, control por voz.","imagen":t("196855"),"url":"https://www.tupi.com.py/producto/196855/","categoria":"Televisores"},
    {"id":"tupi-tv-002","marca":"Tupi","linea":"Televisores","nombre":"TV Midas 50\" UHD Smart Google TV + Soporte","tipo":"Televisor","precio_ref":2240000,"comensales":"—","capacidad":"50\"","descripcion":"Smart TV Google TV 50\" 4K UHD Frameless con soporte incluido. Dolby Audio.","imagen":t("196857"),"url":"https://www.tupi.com.py/producto/196857/","categoria":"Televisores"},
    {"id":"tupi-tv-003","marca":"Tupi","linea":"Televisores","nombre":"TV Midas 55\" UHD Smart Google TV + Soporte","tipo":"Televisor","precio_ref":2566000,"comensales":"—","capacidad":"55\"","descripcion":"Smart TV Google TV 55\" 4K UHD. Frameless, HDR, Control de Voz + Soporte pared.","imagen":t("196859"),"url":"https://www.tupi.com.py/producto/196859/","categoria":"Televisores"},
    {"id":"tupi-tv-004","marca":"Tupi","linea":"Televisores","nombre":"TV Midas 65\" UHD Smart Google TV + Soporte","tipo":"Televisor","precio_ref":4643000,"comensales":"—","capacidad":"65\"","descripcion":"Smart TV Google TV 65\" 4K Frameless. La pantalla más grande de la línea Midas.","imagen":t("196861"),"url":"https://www.tupi.com.py/producto/196861/","categoria":"Televisores"},
    {"id":"tupi-tv-005","marca":"Tupi","linea":"Televisores","nombre":"TV Samsung 40\" Full HD Smart Tizen","tipo":"Televisor","precio_ref":1489000,"comensales":"—","capacidad":"40\"","descripcion":"Samsung 40\" Full HD LED Smart Tizen OS. Para uso comercial y hogar.","imagen":t("216066"),"url":"https://www.tupi.com.py/producto/216066/","categoria":"Televisores"},
    {"id":"tupi-tv-006","marca":"Tupi","linea":"Televisores","nombre":"TV Samsung 32\" The Frame Smart","tipo":"Televisor","precio_ref":3680000,"comensales":"—","capacidad":"32\"","descripcion":"Samsung The Frame 32\" Full HD. Modo Arte, marco intercambiable, diseño cuadro.","imagen":t("101778"),"url":"https://www.tupi.com.py/producto/101778/","categoria":"Televisores"},
    {"id":"tupi-tv-007","marca":"Tupi","linea":"Televisores","nombre":"TV Kenwood 85\" 4K QD-Mini LED Smart Google TV","tipo":"Televisor","precio_ref":9990000,"comensales":"—","capacidad":"85\"","descripcion":"Kenwood 85\" QD-Mini LED 4K Google TV. La mejor experiencia de imagen.","imagen":t("MKP150354"),"url":"https://www.tupi.com.py/producto/MKP150354/","categoria":"Televisores"},
    {"id":"tupi-tv-008","marca":"Tupi","linea":"Televisores","nombre":"TV Samsung 43\" Full HD Smart Tizen","tipo":"Televisor","precio_ref":2230000,"comensales":"—","capacidad":"43\"","descripcion":"Samsung 43\" Smart LED Full HD Tizen OS. Serie T5203. Sonido Dolby.","imagen":t("samsung-43-smart"),"url":"https://www.tupi.com.py/","categoria":"Televisores"},

    # ── Heladeras
    {"id":"tupi-hel-001","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Electrolux 311L 2P c/Dispenser","tipo":"Heladera","precio_ref":2895000,"comensales":"—","capacidad":"311 L","descripcion":"Electrolux 311L 2 puertas frío húmedo con dispenser de agua externo.","imagen":t("59191"),"url":"https://www.tupi.com.py/producto/59191/","categoria":"Heladeras"},
    {"id":"tupi-hel-002","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Consul 360L 2 Puertas Blanco","tipo":"Heladera","precio_ref":2854000,"comensales":"—","capacidad":"360 L","descripcion":"Consul 360L 2 puertas frío húmedo. Blanco, compartimiento de vegetales.","imagen":t("25285"),"url":"https://www.tupi.com.py/producto/25285/","categoria":"Heladeras"},
    {"id":"tupi-hel-003","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Consumer Frigobar 55L Gris","tipo":"Heladera","precio_ref":1376000,"comensales":"—","capacidad":"55 L","descripcion":"Frigobar compacto 55L frío húmedo. Ideal para oficina, cuarto o bar.","imagen":t("27285"),"url":"https://www.tupi.com.py/producto/27285/","categoria":"Heladeras"},
    {"id":"tupi-hel-004","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Consumer Retro 120L Negra","tipo":"Heladera","precio_ref":1942000,"comensales":"—","capacidad":"120 L","descripcion":"Heladera retro vintage 120L diseño italiano. Color negro. Frío húmedo.","imagen":t("39745"),"url":"https://www.tupi.com.py/producto/39745/","categoria":"Heladeras"},
    {"id":"tupi-hel-005","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Electrolux 300L 2 Puertas Blanco","tipo":"Heladera","precio_ref":1885000,"comensales":"—","capacidad":"300 L","descripcion":"Electrolux 300L 2 puertas frío/húmedo. Eficiente y espaciosa para el hogar.","imagen":t("109631"),"url":"https://www.tupi.com.py/producto/109631/","categoria":"Heladeras"},
    {"id":"tupi-hel-006","marca":"Tupi","linea":"Heladeras","nombre":"Heladera JAM 300L 2 Puertas Blanca","tipo":"Heladera","precio_ref":0,"comensales":"—","capacidad":"300 L","descripcion":"JAM 300L 2 puertas frío/húmedo blanca. Excelente relación precio-capacidad.","imagen":t("85054"),"url":"https://www.tupi.com.py/producto/85054/","categoria":"Heladeras"},
    {"id":"tupi-hel-007","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Electrolux 371L No Frost Inox","tipo":"Heladera","precio_ref":3548000,"comensales":"—","capacidad":"371 L","descripcion":"Electrolux 371L neto 2 puertas frío seco. Acero inoxidable, no frost.","imagen":t("77088"),"url":"https://www.tupi.com.py/producto/77088/","categoria":"Heladeras"},
    {"id":"tupi-hel-008","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Frigobar Consul 120L Oficina","tipo":"Heladera","precio_ref":1920000,"comensales":"—","capacidad":"120 L","descripcion":"Frigobar Consul 120L 1 puerta para oficina. Frío húmedo, diseño compacto.","imagen":t("67773"),"url":"https://www.tupi.com.py/producto/67773/","categoria":"Heladeras"},
    {"id":"tupi-hel-009","marca":"Tupi","linea":"Heladeras","nombre":"Mini Visicooler Consumer 120L Doble Vidrio","tipo":"Heladera","precio_ref":2095000,"comensales":"—","capacidad":"120 L","descripcion":"Mini visicooler 120L con puerta de doble vidrio y 3 rejillas. Frío húmedo.","imagen":t("70713"),"url":"https://www.tupi.com.py/producto/70713/","categoria":"Heladeras"},
    {"id":"tupi-hel-010","marca":"Tupi","linea":"Heladeras","nombre":"Heladera Quanta Frigobar 75L","tipo":"Heladera","precio_ref":1222000,"comensales":"—","capacidad":"75 L","descripcion":"Frigobar Quanta 75L temperatura ajustable 220V. Frío húmedo compacto.","imagen":t("111178"),"url":"https://www.tupi.com.py/producto/111178/","categoria":"Heladeras"},

    # ── Freezers / Exhibidoras
    {"id":"tupi-fre-001","marca":"Tupi","linea":"Freezers","nombre":"Freezer Vertical JAM 210L 1 Puerta","tipo":"Freezer","precio_ref":2202000,"comensales":"—","capacidad":"210 L","descripcion":"Freezer vertical JAM blanco 1 puerta 210L comercial / 160L neto.","imagen":t("92971"),"url":"https://www.tupi.com.py/producto/92971/","categoria":"Freezers"},
    {"id":"tupi-fre-002","marca":"Tupi","linea":"Freezers","nombre":"Exhibidora JAM 450L 0° a 6°","tipo":"Exhibidora","precio_ref":4114000,"comensales":"—","capacidad":"450 L","descripcion":"Exhibidora vertical JAM 450L. Temperatura 0° a 6°, frío seco, ideal comercios.","imagen":t("97601"),"url":"https://www.tupi.com.py/producto/97601/","categoria":"Freezers"},

    # ── Aires Acondicionados
    {"id":"tupi-air-001","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado JAM Split 12.000 BTU","tipo":"Aire Acondicionado","precio_ref":2031000,"comensales":"—","capacidad":"12.000 BTU","descripcion":"JAM Split 12.000 BTU frío/calor R410A ECO + kit de instalación incluido.","imagen":t("64867"),"url":"https://www.tupi.com.py/producto/64867/","categoria":"Aires Acondicionados"},
    {"id":"tupi-air-002","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado Midas 12.000 BTU","tipo":"Aire Acondicionado","precio_ref":1897000,"comensales":"—","capacidad":"12.000 BTU","descripcion":"Midas 12.000 BTU frío/calor R410 gas ecológico. Diseño moderno y silencioso.","imagen":t("58705"),"url":"https://www.tupi.com.py/producto/58705/","categoria":"Aires Acondicionados"},
    {"id":"tupi-air-003","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado JAM Split 18.000 BTU","tipo":"Aire Acondicionado","precio_ref":3247000,"comensales":"—","capacidad":"18.000 BTU","descripcion":"JAM Split 18.000 BTU frío/calor R410A ECO + kit de instalación incluido.","imagen":t("64868"),"url":"https://www.tupi.com.py/producto/64868/","categoria":"Aires Acondicionados"},
    {"id":"tupi-air-004","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado JAM 24.000 BTU Split","tipo":"Aire Acondicionado","precio_ref":4825000,"comensales":"—","capacidad":"24.000 BTU","descripcion":"JAM 24.000 BTU Split frío/calor R410A ECO. Para espacios grandes.","imagen":t("58027"),"url":"https://www.tupi.com.py/producto/58027/","categoria":"Aires Acondicionados"},
    {"id":"tupi-air-005","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado JAM 48.000 BTU Piso Techo","tipo":"Aire Acondicionado","precio_ref":11643000,"comensales":"—","capacidad":"48.000 BTU","descripcion":"JAM 48.000 BTU piso techo frío/calor R410A. Para locales y grandes espacios.","imagen":t("57232"),"url":"https://www.tupi.com.py/producto/57232/","categoria":"Aires Acondicionados"},
    {"id":"tupi-air-006","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado JAM 48.000 BTU Cassette","tipo":"Aire Acondicionado","precio_ref":0,"comensales":"—","capacidad":"48.000 BTU","descripcion":"JAM 48.000 BTU cassette empotrable R410A. Distribución uniforme del aire.","imagen":t("76776"),"url":"https://www.tupi.com.py/producto/76776/","categoria":"Aires Acondicionados"},
    {"id":"tupi-air-007","marca":"Tupi","linea":"Aires Acondicionados","nombre":"Aire Acondicionado Portátil Willpex 24.000 BTU","tipo":"Aire Acondicionado","precio_ref":0,"comensales":"—","capacidad":"24.000 BTU","descripcion":"Portátil 24.000 BTU (7000W). Sin instalación, movilidad total. R410A.","imagen":t("197331"),"url":"https://www.tupi.com.py/producto/197331/","categoria":"Aires Acondicionados"},

    # ── Electrodomésticos / Cocina
    {"id":"tupi-elec-001","marca":"Tupi","linea":"Electrodomésticos","nombre":"Air Fryer Electrobras Smart 4.4L","tipo":"Air Fryer","precio_ref":310000,"comensales":"3-4","capacidad":"4.4 L","descripcion":"Freidora de aire 4.4L 1500W. Sin aceite, frituras crocantes y saludables.","imagen":t("98130"),"url":"https://www.tupi.com.py/producto/98130/","categoria":"Electrodomésticos"},
]

MARCAS = ["Essen", "Tupi"]
CATEGORIAS = sorted(set(p["categoria"] for p in CATALOGO))
LINEAS = {
    "Essen": sorted(set(p["linea"] for p in CATALOGO if p["marca"] == "Essen")),
    "Tupi":  sorted(set(p["linea"] for p in CATALOGO if p["marca"] == "Tupi")),
}
